apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegram-sjp.fullname" . }}
  labels:
    {{ include "telegram-sjp.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envVars | nindent 2 }}
